---
collections:
  - name: amazon.aws
    version: 6.5.3
  - name: ansible.posix
  - name: awx.awx
  - name: redhat.rhel_system_roles
  - name: redhat.insights
  - name: community.crypto
  - name: community.aws
  - name: community.general
