---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.controller
  - name: redhat.rhel_system_roles
  - name: redhat.insights
  - name: community.crypto
  - name: community.aws
  - name: community.general
