---
vpc_name: demo_vpc
user_name: mickey.mouse
subnet_name: "{{ vpc_name }}_Subnet"
image: ami-06127bea7af8a9ad8
count: 1
region: us-west-1
assign_public_ip: true
alwaysup: false
instance_type: t2.micro
ec2_security_group_name: "{{ vpc_name }}_SECGRP"
ec2_ansible_group: "{{ user_name }}"
my_email_address: "{{ user_name }}@redhat.com"
my_ssh_key: my-ssh-key
ansible_python_interpreter: /usr/bin/python3
key_purpose: hello-world
key_name: mickeys-key
kms_key_id: b3ff4150-945e-40ae-af19-c73901dc5df6
