---
- name: Create a new KMS key
  amazon.aws.kms_key:
    region: "{{ region }}"
    state: absent
    alias: "{{ key_name }}"
    tags:
      Name: "{{ key_name }}"
      Purpose: "{{ key_purpose }}"