---
- name: Looking up Subnet_id
  register: subnet_id
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      tag:Name: "{{ subnet_name }}"

- name: Setting vpc_subnet_id based on Lookup
  when: vpc_subnet_id is undefined
  ansible.builtin.set_fact:
    vpc_subnet_id: "{{ subnet_id.subnets[0].id }}"

- name: Creating machine instance
  register: ec2_vms
  amazon.aws.ec2_instance:
    name: Linux Demo Server
    region: "{{ region }}"
    key_name: "{{ my_ssh_key }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    instance_type: "{{ instance_type }}"
    security_group: "{{ ec2_security_group_name }}"
    network:
      assign_public_ip: "{{ assign_public_ip }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          kms_key_id: "{{ kms_key_id }}"
          encrypted: true
    image_id: "{{ image }}"
    tags:
      Environment: Linux_deployment
      AlwaysUp: "{{ alwaysup }}"
      Createdby: Ansible Controller
      Contact: "{{ my_email_address }}"
      DeletebBy: "{{ ec2_ansible_group }}"
    wait: true
    wait_timeout: 600

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  loop: "{{ ec2_vms['instances'] }}"
  ansible.builtin.wait_for:
    port: 22
    host: "{{ item['public_ip_address'] }}"
    search_regex: OpenSSH
    delay: 10

# - name: Update the volume
#   loop: "{{ ec2_vms['instances'] }}"
#   amazon.aws.ec2_vol:
#     instance: "{{ item['instance_id'] }}"
#     name: Linux Demo Server
#     region: "{{ region }}"
#     delete_on_termination: true
#     encrypted: true
#     kms_key_id: "{{ kms_key_id }}"