---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python39-devel [platform:rpm]
  python:
    - boto3==1.26.0
    - botocore==1.29.0
  python_interpreter:
        package_system: "python310"
        python_path: "/usr/bin/python3.10"

options:
  package_manager_path: /usr/bin/microdnf
