---
- name: Secure Python Secrets
  hosts: all
  vars_files:
    - secrets.yml
  environment:
    DYNATRACE_API_KEY: "{{ dynatrace_api_key }}"


  tasks:

    - name: Set my API key
      register: my_output
      changed_when: my_output.rc != 0
      ansible.builtin.shell:
        cmd: "echo $DYNATRACE_API_KEY"
