---
- name: Secure Python Secrets
  hosts: all
  vars_files:
    - files/secrets.yml
  environment:
    DYNATRACE_API_KEY: "{{ dynatrace_api_key }}"

  tasks:

    # - name: Set my API key
    #   register: my_output
    #   changed_when: my_output.rc != 0
    #   ansible.builtin.shell:
    #     cmd: echo $DYNATRACE_API_KEY

    - name: Copy my python script into place
      ansible.builtin.copy:
        src: scripts/my_secret.py
        dest: ~/my_secret.py
        mode: '0700'

    - name: Run my python script
      ansible.builtin.command:
        cmd: ~/my_secret.py