---
- name: Shutdown AAP VMs
  hosts: localhost
  connection: local

  tasks:
    - name: Shutdown VMs based on tag filters
      amazon.aws.ec2_instance:
        state: stopped
        filters:
          tag:Environment: AAP_Deployment
          instance-state-name:
            - pending
            - running
        region: "{{ infrastructure_region }}"
