---
- name: Unregister the systems
  hosts: rhel
  become: true

  roles:
    - role: linux_unregister_servers

- name: Delete stuff
  hosts: localhost
  connection: local

  roles:
    - role: delete_vm
    - role: delete_kmskey
    - role: delete_vpc
    - role: inventory_remove_servers
